nopCommerce/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Controllers/PayPalCommerceController.cs
using System.Linq.Expressions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Core.Configuration;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Orders;
using Nop.Core.Http.Extensions;
using Nop.Plugin.Payments.PayPalCommerce.Domain;
using Nop.Plugin.Payments.PayPalCommerce.Factories;
using Nop.Plugin.Payments.PayPalCommerce.Models.Admin;
using Nop.Plugin.Payments.PayPalCommerce.Services;
using Nop.Services;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Payments.PayPalCommerce.Controllers;

[Area(AreaNames.ADMIN)]
[AutoValidateAntiforgeryToken]
[ValidateIpAddress]
[AuthorizeAdmin]
public class PayPalCommerceController : BasePluginController
{
    #region Fields

    private readonly AppSettings _appSettings;
    private readonly IGenericAttributeService _genericAttributeService;
    private readonly ILocalizationService _localizationService;
    private readonly INotificationService _notificationService;
    private readonly IPermissionService _permissionService;
    private readonly ISettingService _settingService;
    private readonly IStoreContext _storeContext;
    private readonly IWorkContext _workContext;
    private readonly PayPalCommerceModelFactory _modelFactory;
    private readonly PayPalCommerceServiceManager _serviceManager;
    private readonly ShoppingCartSettings _shoppingCartSettings;

    #endregion

    #region Ctor

    public PayPalCommerceController(AppSettings appSettings,
        IGenericAttributeService genericAttributeService,
        ILocalizationService localizationService,
        INotificationService notificationService,
        IPermissionService permissionService,
        ISettingService settingService,
        IStoreContext storeContext,
        IWorkContext workContext,
        PayPalCommerceModelFactory modelFactory,
        PayPalCommerceServiceManager serviceManager,
        ShoppingCartSettings shoppingCartSettings)
    {
        _appSettings = appSettings;
        _genericAttributeService = genericAttributeService;
        _localizationService = localizationService;
        _notificationService = notificationService;
        _permissionService = permissionService;
        _settingService = settingService;
        _storeContext = storeContext;
        _workContext = workContext;
        _modelFactory = modelFactory;
        _serviceManager = serviceManager;
        _shoppingCartSettings = shoppingCartSettings;
    }

    #endregion

    #region Utilities

    /// <summary>
    /// Load plugin settings
    /// </summary>
    /// <param name="storeId">Store id; pass null to use active store scope configuration</param>
    /// <returns>
    /// A task that represents the asynchronous operation
    /// The task result contains the plugin settings; store id
    /// </returns>
    private async Task<(PayPalCommerceSettings Settings, int StoreId)> LoadSettingsAsync(int? storeId = null)
    {
        storeId ??= await _storeContext.GetActiveStoreScopeConfigurationAsync();
        var settings = await _settingService.LoadSettingAsync<PayPalCommerceSettings>(storeId ?? 0);

        //we don't need some of the shared settings that loaded above, so load them separately for the chosen store
        if (storeId > 0)
        {
            async Task<TPropType> getSettingAsync<TPropType>(Expression<Func<PayPalCommerceSettings, TPropType>> keySelector) =>
                await _settingService.GetSettingByKeyAsync<TPropType>(_settingService.GetSettingKey(settings, keySelector), storeId: storeId ?? 0);

            settings.MerchantGuid = await getSettingAsync(setting => setting.MerchantGuid);
            settings.MerchantId = await getSettingAsync(setting => setting.MerchantId);
            settings.WebhookUrl = await getSettingAsync(setting => setting.WebhookUrl);
            settings.SetCredentialsManually = await getSettingAsync(setting => setting.SetCredentialsManually);
            settings.UseSandbox = await getSettingAsync(setting => setting.UseSandbox);
            settings.ClientId = await getSettingAsync(setting => setting.ClientId);
            settings.SecretKey = await getSettingAsync(setting => setting.SecretKey);
            settings.ConfiguratorSupported = await getSettingAsync(setting => setting.ConfiguratorSupported);
        }

        return (settings, storeId ?? 0);
    }

    /// <summary>
    /// Save settings for the passed store
    /// </summary>
    /// <typeparam name="TPropType">Property type</typeparam>
    /// <param name="settings">Plugin settings</param>
    /// <param name="keySelector">Key selector</param>
    /// <param name="storeId">Store id</param>
    /// <param name="overrideForStore">Whether to overridde this setting for the passed store</param>
    /// <returns>A task that represents the asynchronous operation</returns>
    private async Task SaveSettingAsync<TPropType>(PayPalCommerceSettings settings,
        Expression<Func<PayPalCommerceSettings, TPropType>> keySelector, int storeId, bool? overrideForStore = null)
    {
        //save overridden settings
        await _settingService.SaveSettingOverridablePerStoreAsync(settings, keySelector, overrideForStore ?? true, storeId, false);

        //save shared settings
        if (storeId > 0 && overrideForStore is null)
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, keySelector, true, 0, false);
    }

    /// <summary>
    /// Get details to sign up a merchant
    /// </summary>
    /// <param name="settings">Plugin settings</param>
    /// <returns>
    /// A task that represents the asynchronous operation
    /// The task result contains the URL to sign up; merchant internal id
    /// </returns>
    private async Task<(string SandboxUrl, string LiveUrl, string MerchantGuid)> GetSignUpDetailsAsync(PayPalCommerceSettings settings)
    {
        if (!string.IsNullOrEmpty(settings.MerchantGuid))
            return (null, null, settings.MerchantGuid);

        //set new GUID
        var merchantGuid = Guid.NewGuid().ToString();

        //prepare URL to sign up
        var ((sandboxUrl, liveUrl), error) = await _serviceManager.PrepareSignUpUrlAsync(merchantGuid);
        if (!string.IsNullOrEmpty(error))
        {
            var locale = await _localizationService.GetResourceAsync("Plugins.Payments.PayPalCommerce.Configuration.Error");
            var errorMessage = string.Format(locale, error, Url.Action("List", "Log"));
            _notificationService.ErrorNotification(errorMessage, false);
        }

        return (sandboxUrl, liveUrl, merchantGuid);
    }

    /// <summary>
    /// Check the merchant status
    /// </summary>
    /// <param name="settings">Plugin settings</param>
    /// <param name="storeId">Store id</param>
    /// <returns>
    /// A task that represents the asynchronous operation
    /// The task result contains the merchant model
    /// </returns>
    private async Task<MerchantModel> CheckMerchantStatusAsync(PayPalCommerceSettings settings, int storeId)
    {
        //no need to check the status when credentials were manually set
        if (string.IsNullOrEmpty(settings.MerchantGuid) || settings.SetCredentialsManually)
            return new();

        var model = await _modelFactory.PrepareMerchantModelAsync(settings);

        //disable appropriate settings when unavailable
        if (settings.ConfiguratorSupported != model.ConfiguratorSupported)
        {
            settings.ConfiguratorSupported = model.ConfiguratorSupported;
            await SaveSettingAsync(settings, setting => setting.ConfiguratorSupported, storeId);
        }
        if (!model.AdvancedCardsEnabled && settings.UseCardFields)
        {
            settings.UseCardFields = false;
            await SaveSettingAsync(settings, setting => setting.UseCardFields, storeId);
        }
        if (!model.ApplePayEnabled && settings.UseApplePay)
        {
            settings.UseApplePay = false;
            await SaveSettingAsync(settings, setting => setting.UseApplePay, storeId);
        }
        if (!model.GooglePayEnabled && settings.UseGooglePay)
        {
            settings.UseGooglePay = false;
            await SaveSettingAsync(settings, setting => setting.UseGooglePay, storeId);
        }
        if (!model.VaultingEnabled && settings.UseVault)
        {
            settings.UseVault = false;
            await SaveSettingAsync(settings, setting => setting.UseVault, storeId);
        }
        await _settingService.ClearCacheAsync();

        //display notifications
        foreach (var warning in model.Messages.Warning)
        {
            _notificationService.WarningNotification(warning, false);
        }

        foreach (var error in model.Messages.Error)
        {
            _notificationService.ErrorNotification(error, false);
        }

        foreach (var message in model.Messages.Success)
        {
            _notificationService.SuccessNotification(message);
        }

        return model;
    }

    /// <summary>
    /// Set credentials manually
    /// </summary>
    /// <param name="model">Configuration model</param>
    /// <param name="settings">Plugin settings</param>
    /// <param name="storeId">Store id</param>
    /// <returns>A task that represents the asynchronous operation</returns>
    private async Task SetCredentialsManuallyAsync(ConfigurationModel model, PayPalCommerceSettings settings, int storeId)
    {
        if (!model.SetCredentialsManually)
            return;

        //first delete the unused webhook on a previous client, if changed
        if (PayPalCommerceServiceManager.IsConnected(settings) && !string.Equals(model.ClientId, settings.ClientId))
        {
            await _serviceManager.DeleteWebhookAsync(settings);

nopCommerce/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Views/Admin/PayLater.cshtml
@model PayLaterConfigurationModel

@{
    Layout = "_ConfigurePlugin";
    NopHtml.SetActiveMenuItemSystemName($"{PayPalCommerceDefaults.SystemName} Pay Later");
}

@await Component.InvokeAsync(typeof(StoreScopeConfigurationViewComponent))

<script src="@PayPalCommerceDefaults.MerchantConfiguratorScriptUrl" defer></script>

<div class="cards-group">
    <div class="card card-default">
        <div class="card-body">
            <div id="messaging-configurator"></div>
        </div>
    </div>
</div>

<script asp-asp-location="Footer">
    $(function () {
        window.merchantConfigurators?.Messaging({
            config: @Html.Raw(Model.Config),
            locale: '@Model.Locale',
            merchantIdentifier: '@Model.ClientId',
            partnerClientId: '@(Model.UseSandbox ? PayPalCommerceDefaults.Onboarding.ClientId.Sandbox : PayPalCommerceDefaults.Onboarding.ClientId.Live)',
            partnerName: 'nopCommerce',
            bnCode: '@PayPalCommerceDefaults.PartnerHeader.Value',
            placements: ['product', 'cart', 'checkout'],
            onSave: (data) => {
                var postData = {
                    config: JSON.stringify(data.config)
                };
                addAntiForgeryToken(postData);
                $.ajax({
                    async: false,
                    type: 'POST',
                    url: '@(Url.Action("PayLaterConfig", "PayPalCommerce"))',
                    data: postData,
                    success: function (response, textStatus, jqXHR) {
                        if (response.error) {
                            displayBarNotification(response.error, 'danger');
                        } else {
                            displayBarNotification(response.message, 'success');
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        if (errorThrown) {
                            displayBarNotification(errorThrown, 'danger');
                        } else {
                            displayBarNotification(textStatus, 'danger');
                        }
                    }
                });
            }
        });
    });

    function displayBarNotification(message, messagetype) {
        $('.content-wrapper').prepend('<div class="alert alert-' + messagetype + ' alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>' + message + '</div>');
    }
</script>

nopCommerce/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Views/Admin/_PaymentMethod.cshtml
@model bool

<div id="card-paypalcommerce" class="card card-default">
    <div class="card-body">
        <div class="form-group row">
            @if (!Model)
            {
                <div class="col-md-8">
                    <div style="padding: 10px 0; font-style: italic; font-weight: bolder; font-size: larger;">
                        <i class="far fa-dot-circle" style="color: #FFD140;"></i>
                        <span>Recommended</span>
                    </div>
                    <div style=" display: flex; justify-content: left; padding-bottom: 10px;">
                        <a href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;"><img src="https://www.paypalobjects.com/webstatic/mktg/Logo/pp-logo-200px.png" border="0" alt="PayPal Logo"></a>
                    </div>
                    <br />
                    <span style="font-size: large;"><b>PayPal: The all-in-one checkout solution</b></span>
                    <br /><br />
                    <ul>
                        <li>Help drive conversion by offering customers a seamless checkout experience with no setup or monthly fees.</li>
                        <li>Provide buy now pay later solutions at no extra cost.</li>
                        <li>Securely accept all major credit/debit cards and local payment methods with the strength of the PayPal network.</li>
                    </ul>
                    <br />
                    <a id="configure-paypalcommerce-button" href="@Url.Action("Configure", "PayPalCommerce")" class="btn btn-primary">
                        Get started
                    </a>
                </div>
                <div class="col-md-4">
                    <div style="display: flex;justify-content: right;">
                        <a href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;"><img src="https://www.paypalobjects.com/webstatic/mktg/logo/AM_mc_vs_dc_ae.jpg" border="0" alt="PayPal Acceptance Mark"></a>
                    </div>
                </div>
            }
            else
            {
                <div class="col-md-3">
                    <div style="padding: 10px 0; font-style: italic; font-weight: bolder; font-size: larger;">
                        <i class="far fa-dot-circle" style="color: #FFD140;"></i>
                        <span>Recommended</span>
                    </div>
                    <div style=" display: flex; justify-content: left; padding-bottom: 10px;">
                        <a href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;"><img src="https://www.paypalobjects.com/webstatic/mktg/Logo/pp-logo-200px.png" border="0" alt="PayPal Logo"></a>
                    </div>
                </div>
                <div class="col-md-5">
                    <br />
                    <span style="font-size: large;"><b>PayPal: The all-in-one checkout solution</b></span><br /><br />
                    <i class="fas fa-check true-icon" nop-value="true"></i><span style="padding-left: 10px;">Your PayPal account is connected</span>
                    <br />
                    <br />
                    <a href="@Url.Action("Configure", "PayPalCommerce")" class="btn btn-primary">
                        Configure
                    </a>
                </div>
                <div class="col-md-4">
                    <div style="display: flex;justify-content: right;">
                        <a href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;"><img src="https://www.paypalobjects.com/webstatic/mktg/logo/AM_mc_vs_dc_ae.jpg" border="0" alt="PayPal Acceptance Mark"></a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

nopCommerce/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Views/Admin/_ShipmentCarrier.cshtml
@model ShipmentCarrierModel

<div id="paypal-carrier" class="form-group row">
    <div class="col-md-3">
        <nop-label asp-for="PayPalCommerceShipmentCarrier" />
    </div>
    <div class="col-md-9">
        <nop-editor asp-for="PayPalCommerceShipmentCarrier" asp-required="true" />
        <span asp-validation-for="PayPalCommerceShipmentCarrier"></span>
    </div>
</div>
<div id="paypal-carrier-info" class="form-group row">
    <div class="col-md-9 offset-md-3">
        <span>NOTE: The carrier for the shipment is required. Some carriers have a global version as well as local subsidiaries. The subsidiaries are repeated over many countries and might also have an entry in the global list. Choose the carrier for your country. If the carrier is not available for your country, choose the global version of the carrier. If your carrier name is not in the list, set carrier to OTHER. For allowed values, see <a href="https://developer.paypal.com/docs/tracking/reference/carriers/" target="_blank">Carriers</a>.</span>
    </div>
</div>

<script>
    $(function () {
        $('#@Html.IdFor(model => model.TrackingNumber)').closest('.form-group').after($('#paypal-carrier'));
        $('#paypal-carrier').after($('#paypal-carrier-info'));
    });
</script>