nopCommerce/src/Presentation/Nop.Web/Areas/Admin/Models/Payments/PaymentMethodListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Payments;

/// <summary>
/// Represents a payment method list model
/// </summary>
public partial record PaymentMethodListModel : BasePagedListModel<PaymentMethodModel>
{
}

nopCommerce/src/Presentation/Nop.Web/Areas/Admin/Models/Payments/PaymentMethodModel.cs
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Web.Areas.Admin.Models.Payments;

/// <summary>
/// Represents a payment method model
/// </summary>
public partial record PaymentMethodModel : BaseNopModel, IPluginModel
{
    #region Properties

    [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.FriendlyName")]
    public string FriendlyName { get; set; }

    [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SystemName")]
    public string SystemName { get; set; }

    [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.DisplayOrder")]
    public int DisplayOrder { get; set; }

    [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.IsActive")]
    public bool IsActive { get; set; }

    [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Configure")]
    public string ConfigurationUrl { get; set; }

    [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.Logo")]
    public string LogoUrl { get; set; }

    [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SupportCapture")]
    public bool SupportCapture { get; set; }

    [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SupportPartiallyRefund")]
    public bool SupportPartiallyRefund { get; set; }

    [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SupportRefund")]
    public bool SupportRefund { get; set; }

    [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SupportVoid")]
    public bool SupportVoid { get; set; }

    [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.RecurringPaymentType")]
    public string RecurringPaymentType { get; set; }

    #endregion
}

nopCommerce/src/Presentation/Nop.Web/Areas/Admin/Models/Payments/PaymentMethodRestrictionModel.cs
using Nop.Web.Areas.Admin.Models.Directory;
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Payments;

/// <summary>
/// Represents a payment method restriction model
/// </summary>
public partial record PaymentMethodRestrictionModel : BaseNopModel
{
    #region Ctor

    public PaymentMethodRestrictionModel()
    {
        AvailablePaymentMethods = new List<PaymentMethodModel>();
        AvailableCountries = new List<CountryModel>();
        Restricted = new Dictionary<string, IDictionary<int, bool>>();
    }

    #endregion

    #region Properties

    public IList<PaymentMethodModel> AvailablePaymentMethods { get; set; }

    public IList<CountryModel> AvailableCountries { get; set; }

    //[payment method system name] / [customer role id] / [restricted]
    public IDictionary<string, IDictionary<int, bool>> Restricted { get; set; }

    #endregion
}

nopCommerce/src/Presentation/Nop.Web/Areas/Admin/Models/Payments/PaymentMethodSearchModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Payments;

/// <summary>
/// Represents a payment method search model
/// </summary>
public partial record PaymentMethodSearchModel : BaseSearchModel
{
}

nopCommerce/src/Presentation/Nop.Web/Areas/Admin/Models/Payments/PaymentMethodsModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Payments;

/// <summary>
/// Represents a payment methods model
/// </summary>
public partial record PaymentMethodsModel : BaseNopModel
{
    #region Ctor

    public PaymentMethodsModel()
    {
        PaymentsMethod = new PaymentMethodSearchModel();
        PaymentMethodRestriction = new PaymentMethodRestrictionModel();
    }

    #endregion

    #region Properties

    public PaymentMethodSearchModel PaymentsMethod { get; set; }

    public PaymentMethodRestrictionModel PaymentMethodRestriction { get; set; }

    #endregion
}

nopCommerce/src/Presentation/Nop.Web/Areas/Admin/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Nop.Core;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Payments;
using Nop.Core.Events;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Payments;
using Nop.Services.Plugins;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Models.Payments;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers;

public partial class PaymentController : BaseAdminController
{
    #region Fields

    protected readonly ICountryService _countryService;
    protected readonly IEventPublisher _eventPublisher;
    protected readonly ILocalizationService _localizationService;
    protected readonly INotificationService _notificationService;
    protected readonly IPaymentModelFactory _paymentModelFactory;
    protected readonly IPaymentPluginManager _paymentPluginManager;
    protected readonly IPermissionService _permissionService;
    protected readonly ISettingService _settingService;
    protected readonly IGenericAttributeService _genericAttributeService;
    protected readonly IWorkContext _workContext;
    protected readonly PaymentSettings _paymentSettings;
    private static readonly char[] _separator = [','];

    #endregion

    #region Ctor

    public PaymentController(ICountryService countryService,
        IEventPublisher eventPublisher,
        ILocalizationService localizationService,
        INotificationService notificationService,
        IPaymentModelFactory paymentModelFactory,
        IPaymentPluginManager paymentPluginManager,
        IPermissionService permissionService,
        ISettingService settingService,
        IGenericAttributeService genericAttributeService,
        IWorkContext workContext,
        PaymentSettings paymentSettings)
    {
        _countryService = countryService;
        _eventPublisher = eventPublisher;
        _localizationService = localizationService;
        _notificationService = notificationService;
        _paymentModelFactory = paymentModelFactory;
        _paymentPluginManager = paymentPluginManager;
        _permissionService = permissionService;
        _settingService = settingService;
        _genericAttributeService = genericAttributeService;
        _workContext = workContext;
        _paymentSettings = paymentSettings;
    }

    #endregion

    #region Methods  

    public virtual IActionResult PaymentMethods()
    {
        return RedirectToAction("Methods");
    }

    [CheckPermission(StandardPermission.Configuration.MANAGE_PAYMENT_METHODS)]
    public virtual async Task<IActionResult> Methods(bool showtour = false)
    {
        //prepare model
        var model = await _paymentModelFactory.PreparePaymentMethodsModelAsync(new PaymentMethodsModel());

        //show configuration tour
        if (showtour)
        {
            var customer = await _workContext.GetCurrentCustomerAsync();
            var hideCard = await _genericAttributeService.GetAttributeAsync<bool>(customer, NopCustomerDefaults.HideConfigurationStepsAttribute);
            var closeCard = await _genericAttributeService.GetAttributeAsync<bool>(customer, NopCustomerDefaults.CloseConfigurationStepsAttribute);

            if (!hideCard && !closeCard)
                ViewBag.ShowTour = true;
        }

        return View(model);
    }

    [HttpPost]
    [CheckPermission(StandardPermission.Configuration.MANAGE_PAYMENT_METHODS)]
    public virtual async Task<IActionResult> Methods(PaymentMethodSearchModel searchModel)
    {
        //prepare model
        var model = await _paymentModelFactory.PreparePaymentMethodListModelAsync(searchModel);

        return Json(model);
    }

    [HttpPost]
    [CheckPermission(StandardPermission.Configuration.MANAGE_PAYMENT_METHODS)]
    public virtual async Task<IActionResult> MethodUpdate(PaymentMethodModel model)
    {
        var pm = await _paymentPluginManager.LoadPluginBySystemNameAsync(model.SystemName);
        if (_paymentPluginManager.IsPluginActive(pm))
        {
            if (!model.IsActive)
            {
                //mark as disabled
                _paymentSettings.ActivePaymentMethodSystemNames.Remove(pm.PluginDescriptor.SystemName);
                await _settingService.SaveSettingAsync(_paymentSettings);
            }
        }
        else
        {
            if (model.IsActive)
            {
                //mark as active
                _paymentSettings.ActivePaymentMethodSystemNames.Add(pm.PluginDescriptor.SystemName);
                await _settingService.SaveSettingAsync(_paymentSettings);
            }
        }

        var pluginDescriptor = pm.PluginDescriptor;
        pluginDescriptor.FriendlyName = model.FriendlyName;
        pluginDescriptor.DisplayOrder = model.DisplayOrder;

        //update the description file
        pluginDescriptor.Save();

        //raise event
        await _eventPublisher.PublishAsync(new PluginUpdatedEvent(pluginDescriptor));

        return new NullJsonResult();
    }

    [CheckPermission(StandardPermission.Configuration.MANAGE_PAYMENT_METHODS)]
    public virtual async Task<IActionResult> MethodRestrictions()
    {
        //prepare model
        var model = await _paymentModelFactory.PreparePaymentMethodsModelAsync(new PaymentMethodsModel());

        return View(model);
    }

    //we ignore this filter for increase RequestFormLimits
    [IgnoreAntiforgeryToken]
    //we use 2048 value because in some cases default value (1024) is too small for this action
    [RequestFormLimits(ValueCountLimit = 2048)]
    [HttpPost, ActionName("MethodRestrictions")]
    [CheckPermission(StandardPermission.Configuration.MANAGE_PAYMENT_METHODS)]
    public virtual async Task<IActionResult> MethodRestrictionsSave(PaymentMethodsModel model, IFormCollection form)
    {
        var paymentMethods = await _paymentPluginManager.LoadAllPluginsAsync();
        var countries = await _countryService.GetAllCountriesAsync(showHidden: true);

        foreach (var pm in paymentMethods)
        {
            var formKey = "restrict_" + pm.PluginDescriptor.SystemName;
            var countryIdsToRestrict = (!StringValues.IsNullOrEmpty(form[formKey])
                    ? form[formKey].ToString().Split(_separator, StringSplitOptions.RemoveEmptyEntries).ToList()
                    : new List<string>())
                .Select(x => Convert.ToInt32(x)).ToList();

            var newCountryIds = new List<int>();
            foreach (var c in countries)
            {
                if (countryIdsToRestrict.Contains(c.Id))
                {
                    newCountryIds.Add(c.Id);
                }
            }

            await _paymentPluginManager.SaveRestrictedCountriesAsync(pm, newCountryIds);
        }

        _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Configuration.Payment.MethodRestrictions.Updated"));

        return RedirectToAction("MethodRestrictions");
    }

    #endregion
}

nopCommerce/src/Presentation/Nop.Web/Areas/Admin/Views/Payment/MethodRestrictions.cshtml
@model PaymentMethodsModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Configuration.Payment.MethodRestrictions").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Payment restrictions");
}

<form asp-controller="Payment" asp-action="MethodRestrictions" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Configuration.Payment.MethodRestrictions")
        </h1>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <div class="form-horizontal">
                    <div class="cards-group">
                        @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.PaymentMethodRestrictionsTop, additionalData = Model })
                        <div class="card card-default">
                            <div class="card-body">
                                <div class="row v-center margin-b-5">
                                    <div class="col-sm-10 col-xs-9">
                                        <nop-doc-reference asp-string-resource="@T("Admin.Documentation.Reference.PaymentMethodRestrictions", Docs.PaymentMethodRestrictions + Utm.OnAdmin)" />

                                        @T("Admin.Configuration.Payment.MethodRestrictions.Description")
                                    </div>
                                    <div class="col-sm-2 col-xs-3">
                                        <button type="submit" name="save" class="btn btn-primary float-right">
                                            <i class="far fa-floppy-disk"></i>
                                            @T("Admin.Common.Save")
                                        </button>
                                        @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.PaymentsListButtons, additionalData = Model })
                                    </div>
                                </div>

                                @if (!Model.PaymentMethodRestriction.AvailablePaymentMethods.Any())
                                {
                                    <text>No payment methods installed</text>
                                }
                                else if (!Model.PaymentMethodRestriction.AvailableCountries.Any())
                                {
                                    <text>No countries available</text>
                                }
                                else
                                {
                                    <script>
                                $(function() {
                                    @foreach (var pm in Model.PaymentMethodRestriction.AvailablePaymentMethods)
                                    {
                                        var systemNameWithoutDot = pm.SystemName.Replace(".", "");
                                        <text>
                                            prepareTableCheckboxes('#selectall-@(systemNameWithoutDot)', '.restrict_@(systemNameWithoutDot)');
                                        </text>
                                    }
                                });
                                    </script>
                                    <table class="table table-hover table-bordered table-striped">
                                        <tbody>
                                            <tr>
                                                <th scope="col" style="padding-top: 14px;">
                                                    <strong>@T("Admin.Configuration.Payment.MethodRestrictions.Country")</strong>
                                                </th>
                                                @foreach (var pm in Model.PaymentMethodRestriction.AvailablePaymentMethods)
                                                {
                                                    var systemNameWithoutDot = pm.SystemName.Replace(".", "");
                                                    <th scope="col">
                                                        <div class="checkbox">
                                                            <label>
                                                                <input type="checkbox" id="selectall-@(systemNameWithoutDot)" />
                                                                <strong>@pm.FriendlyName</strong>
                                                            </label>
                                                        </div>
                                                    </th>
                                                }
                                            </tr>
                                            @foreach (var c in Model.PaymentMethodRestriction.AvailableCountries)
                                            {
                                                <tr>
                                                    <td>
                                                        <span>@c.Name</span>
                                                    </td>
                                                    @foreach (var pm in Model.PaymentMethodRestriction.AvailablePaymentMethods)
                                                    {
                                                        var restricted = Model.PaymentMethodRestriction.Restricted.ContainsKey(pm.SystemName) && Model.PaymentMethodRestriction.Restricted[pm.SystemName][c.Id];
                                                        var systemNameWithoutDot = pm.SystemName.Replace(".", "");
                                                        <td>
                                                            <input class="restrict_@(systemNameWithoutDot)" type="checkbox" value="@(c.Id)" name="restrict_@(pm.SystemName)" @(restricted ? " checked=checked" : null) />
                                                        </td>
                                                    }
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                }
                            </div>
                        </div>
                        @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.PaymentMethodRestrictionsBottom, additionalData = Model })
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>

nopCommerce/src/Presentation/Nop.Web/Areas/Admin/Views/Payment/Methods.cshtml
@model PaymentMethodsModel
@using Nop.Web.Framework.Models.AdminAreaTour

@{
    //page title
    ViewBag.PageTitle = T("Admin.Configuration.Payment.Methods").Text;
    //tour step
    ViewBag.TourStep = TourStep.PaymentMethods;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Payment methods");
}

@await Html.PartialAsync("_AdminTour")

<div class="content-header clearfix">
    <h1 class="float-left">
        @T("Admin.Configuration.Payment.Methods")
    </h1>
</div>

<section class="content">
    <div class="container-fluid">
        <div class="form-horizontal">
            <div class="cards-group">
                @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.PaymentMethodListTop, additionalData = Model })
                <div class="card card-default">
                    <div class="card-body">
                        <p>
                            <nop-doc-reference asp-string-resource="@T("Admin.Documentation.Reference.PaymentMethods", Docs.PaymentMethods + Utm.OnAdmin)" asp-add-wrapper="false"/>
                            @T("Admin.Configuration.Payment.Methods.DownloadMorePlugins", OfficialSite.PaymentPlugins + Utm.OnAdminPaymentPlugins.Replace('?', '&'))
                        </p>

                        <div id="payment-methods-area">
                            @await Html.PartialAsync("Table", new DataTablesModel
                            {
                                Name = "paymentmethods-grid",
                                RowIdBasedOnField = nameof(PaymentMethodModel.SystemName),
                                UrlRead = new DataUrl("Methods", "Payment", null),
                                UrlUpdate = new DataUrl("MethodUpdate", "Payment", null),
                                Length = Model.PaymentsMethod.PageSize,
                                LengthMenu = Model.PaymentsMethod.AvailablePageSizes,
                                ColumnCollection = new List<ColumnProperty>
                                    {
                                        new ColumnProperty(nameof(PaymentMethodModel.FriendlyName))
                                        {
                                            Title = T("Admin.Configuration.Payment.Methods.Fields.FriendlyName").Text,
                                            Editable = true,
                                            EditType = EditType.String
                                        },
                                        new ColumnProperty(nameof(PaymentMethodModel.SystemName))
                                        {
                                            Title = T("Admin.Configuration.Payment.Methods.Fields.SystemName").Text,
                                            Width = "100"
                                        },
                                        new ColumnProperty(nameof(PaymentMethodModel.SupportCapture))
                                        {
                                            Title = T("Admin.Configuration.Payment.Methods.Fields.SupportCapture").Text,
                                            Width = "100",
                                            ClassName = NopColumnClassDefaults.CenterAll,
                                            Render = new RenderBoolean()
                                        },
                                        new ColumnProperty(nameof(PaymentMethodModel.SupportRefund))
                                        {
                                            Title = T("Admin.Configuration.Payment.Methods.Fields.SupportRefund").Text,
                                            Width = "100",
                                            ClassName = NopColumnClassDefaults.CenterAll,
                                            Render = new RenderBoolean()
                                        },
                                        new ColumnProperty(nameof(PaymentMethodModel.SupportPartiallyRefund))
                                        {
                                            Title = T("Admin.Configuration.Payment.Methods.Fields.SupportPartiallyRefund").Text,
                                            Width = "100",
                                            ClassName = NopColumnClassDefaults.CenterAll,
                                            Render = new RenderBoolean()
                                        },
                                        new ColumnProperty(nameof(PaymentMethodModel.SupportVoid))
                                        {
                                            Title = T("Admin.Configuration.Payment.Methods.Fields.SupportVoid").Text,
                                            Width = "100",
                                            ClassName = NopColumnClassDefaults.CenterAll,
                                            Render = new RenderBoolean()
                                        },
                                        new ColumnProperty(nameof(PaymentMethodModel.RecurringPaymentType))
                                        {
                                            Title = T("Admin.Configuration.Payment.Methods.Fields.RecurringPaymentType").Text,
                                            Width = "150"
                                        },
                                        new ColumnProperty(nameof(PaymentMethodModel.DisplayOrder))
                                        {
                                            Title = T("Admin.Configuration.Payment.Methods.Fields.DisplayOrder").Text,
                                            Width = "100",
                                            ClassName = NopColumnClassDefaults.CenterAll,
                                            Editable = true,
                                            EditType = EditType.Number
                                        },
                                        new ColumnProperty(nameof(PaymentMethodModel.IsActive))
                                        {
                                            Title = T("Admin.Configuration.Payment.Methods.Fields.IsActive").Text,
                                            Width = "100",
                                            ClassName = NopColumnClassDefaults.CenterAll,
                                            Render = new RenderBoolean(),
                                            Editable = true,
                                            EditType = EditType.Checkbox
                                        },
                                        new ColumnProperty(nameof(PaymentMethodModel.SystemName))
                                        {
                                            Title = T("Admin.Configuration.Payment.Methods.Configure").Text,
                                            Width = "120",
                                            ClassName =  NopColumnClassDefaults.Button + " column-configure",
                                            Render = new RenderCustom("renderColumnConfigure")
                                        },
                                        new ColumnProperty(nameof(PaymentMethodModel.SystemName))
                                        {
                                            Title = T("Admin.Common.Edit").Text,
                                            Width = "80",
                                            ClassName =  NopColumnClassDefaults.Button + " column-edit",
                                            Render = new RenderButtonsInlineEdit()
                                        }
                                    }
                            })
                        </div>
                        <script>
                        function renderColumnConfigure(data, type, row, meta) {
                            if (row.ConfigurationUrl && row.ConfigurationUrl.length > 0) {
                                return '<a class="btn btn-default" href="' + row.ConfigurationUrl + '"><i class="fas fa-gear"></i>@T("Admin.Configuration.Payment.Methods.Configure").Text</a>';
                            } else {
                                return '';
                            }
                        }
                        </script>
                    </div>
                </div>
                @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.PaymentMethodListBottom, additionalData = Model })
            </div>
        </div>
    </div>
</section>